### ISSUE TITLE
Error Deploying With Websauna.Ansible

### ISSUE THREAD

**Issue by ooduor** [websauna/cookiecutter-websauna-app#1]
* cookiecutter-websauna-app version: 1.0.0a1
* Python version: 3.5

### Description

I've managed to create an app using cookiecutter but encountering a deployment issue I believe due to the structure of the app. For example the full path to conf folder on my local setup is `/home/anthony/mycompany.myproject/mycompany/myproject/conf`. The _setup.py_ and _requirements.txt_ are here `/home/anthony/mycompany.myproject/` but on deployment as is with websauna.ansible, it expects to find conf at `/home/anthony/mycompany.myproject/myproject/conf`. The package/path namespace syntax seems not aligned with the ansible scripts or how would I update my playbook to get it right?
I updated my playbook accordingly without success:
```
  vars:
    - package_name: mycompany
    - site_id: myproject
```
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
~$ ansible-playbook -i hosts.ini playbook-myproject.yml
...
TASK [websauna.site : Install Python packages] *********************************
fatal: [myproject_production]: FAILED! => {"changed": true, "cmd": ["/srv/pyramid/mycompany/venv/bin/pip", "install", "--no-input", "-r", "/srv/pyramid/mycompany/requirements.txt", "--index-url=https://pypi.python.org/simple"], "delta": "0:00:00.376857", "end": "2017-10-21 04:50:22.870780", "failed": true, "rc": 1, "start": "2017-10-21 04:50:22.493923", "stderr": "Directory '.' is not installable. File 'setup.py' not found.", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by ericof** [comment]
There is a new branch on websauna.ansible that supports this cookiecutter.
Please take a look at https://github.com/websauna/websauna.ansible/tree/cookiecutter-support
