### ISSUE TITLE
Newly created app uses unreleased version of websauna

### ISSUE THREAD

**Issue by enkidulan** [websauna/cookiecutter-websauna-app#4]
* cookiecutter-websauna-app version: Tags are missing in this repo, not sure what I should write here
* Python version: any

### Description

*Expectation*: newly create app uses the latest released version of websauna
*Reality*: the app uses an unreleased version of websauna
 *Cause*: In [`requirements.txt`](
https://github.com/websauna/cookiecutter-websauna-app/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/requirements.txt#L1)  websauna is set to be installed from source in editable mode:

```
-e "git+https://github.com/websauna/websauna.git@master#egg=websauna[dev,celery,utils,notebook]"
```

**Comment by ericof** [comment]
We are now using the released version of Websauna
